<?php

namespace App\Http\Controllers\System;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Response;

class BackupController extends Controller
{
    public function index()
    {
        return view('system.backup.index');
    }

    public function download()
    {
        try {
            $database = env('DB_DATABASE');
            $filename = 'db_backup-' . date('d-m-Y_H-i-s') . '.sql';
            $backupPath = storage_path("app/backups");

            if (!File::exists($backupPath)) {
                File::makeDirectory($backupPath, 0755, true);
            }

            $filepath = $backupPath . '/' . $filename;

            $tables = DB::select('SHOW TABLES');
            $tableKey = 'Tables_in_' . $database;

            $sql = "-- Database Backup\n";
            $sql .= "-- Date: " . date('Y-m-d H:i:s') . "\n";
            $sql .= "-- Database: {$database}\n";
            $sql .= "-- Generated by: " . auth()->user()->name . "\n\n";
            $sql .= "SET FOREIGN_KEY_CHECKS=0;\n";
            $sql .= "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n";
            $sql .= "START TRANSACTION;\n";
            $sql .= "SET time_zone = \"+00:00\";\n\n";

            foreach ($tables as $table) {
                $tableName = $table->$tableKey;

                $createTable = DB::select("SHOW CREATE TABLE `{$tableName}`");
                $sql .= "\n-- --------------------------------------------------------\n\n";
                $sql .= "-- Table structure for table `{$tableName}`\n--\n\n";
                $sql .= "DROP TABLE IF EXISTS `{$tableName}`;\n";
                $sql .= $createTable[0]->{'Create Table'} . ";\n\n";

                $rows = DB::table($tableName)->get();

                if ($rows->count() > 0) {
                    $sql .= "-- Dumping data for table `{$tableName}`\n--\n\n";

                    foreach ($rows as $row) {
                        $row = (array) $row;
                        $columns = array_keys($row);
                        $values = array_values($row);

                        $values = array_map(function ($value) {
                            if (is_null($value)) {
                                return 'NULL';
                            }

                            $value = str_replace(
                                ['\\', "\0", "\n", "\r", "'", '"', "\x1a"],
                                ['\\\\', '\\0', '\\n', '\\r', "\\'", '\\"', '\\Z'],
                                $value
                            );
                            return "'" . $value . "'";
                        }, $values);

                        $sql .= "INSERT INTO `{$tableName}` (`" . implode('`, `', $columns) . "`) VALUES (" . implode(', ', $values) . ");\n";
                    }

                    $sql .= "\n";
                }
            }

            $sql .= "SET FOREIGN_KEY_CHECKS=1;\n";
            $sql .= "COMMIT;\n";

            File::put($filepath, $sql);

            Log::info('Database backup created', [
                'filename' => $filename,
                'size' => File::size($filepath),
                'user' => auth()->user()->name
            ]);

            return response()->download($filepath, $filename, [
                'Content-Type' => 'application/sql',
                'Content-Disposition' => 'attachment; filename="' . $filename . '"'
            ]);
        } catch (\Exception $e) {
            Log::error('Backup failed: ' . $e->getMessage());
            session()->flash('failed_message', 'Gagal membuat backup database: ' . $e->getMessage());
            return redirect()->back();
        }
    }

    public function list()
    {
        $backupPath = storage_path("app/backups");

        if (!File::exists($backupPath)) {
            return response()->json(['data' => []]);
        }

        $files = File::files($backupPath);
        $backups = [];

        foreach ($files as $file) {
            if ($file->getExtension() === 'sql') {
                $backups[] = [
                    'name' => $file->getFilename(),
                    'size' => $this->formatBytes($file->getSize()),
                    'size_bytes' => $file->getSize(),
                    'date' => date('d M Y H:i:s', $file->getMTime()),
                    'timestamp' => $file->getMTime()
                ];
            }
        }

        usort($backups, function ($a, $b) {
            return $b['timestamp'] - $a['timestamp'];
        });

        return response()->json([
            'data' => $backups,
            'total' => count($backups),
            'total_size' => $this->formatBytes(array_sum(array_column($backups, 'size_bytes')))
        ]);
    }

    public function downloadExisting($filename)
    {
        try {
            if (strpos($filename, '..') !== false || strpos($filename, '/') !== false) {
                abort(404);
            }

            $filepath = storage_path("app/backups/{$filename}");

            if (!File::exists($filepath)) {
                abort(404);
            }

            return response()->download($filepath, $filename, [
                'Content-Type' => 'application/sql',
                'Content-Disposition' => 'attachment; filename="' . $filename . '"'
            ]);
        } catch (\Exception $e) {
            abort(404);
        }
    }

    public function deleteBackup($filename)
    {
        try {
            if (strpos($filename, '..') !== false || strpos($filename, '/') !== false) {
                return response()->json([
                    'success' => false,
                    'message' => 'Nama file tidak valid.'
                ], 400);
            }

            $filepath = storage_path("app/backups/{$filename}");

            if (File::exists($filepath)) {
                File::delete($filepath);

                Log::info('Backup deleted', [
                    'filename' => $filename,
                    'user' => auth()->user()->name
                ]);

                return response()->json([
                    'success' => true,
                    'message' => 'Backup berhasil dihapus.'
                ]);
            } else {
                return response()->json([
                    'success' => false,
                    'message' => 'File backup tidak ditemukan.'
                ], 404);
            }
        } catch (\Exception $e) {
            Log::error('Delete backup failed: ' . $e->getMessage());
            return response()->json([
                'success' => false,
                'message' => 'Gagal menghapus backup: ' . $e->getMessage()
            ], 500);
        }
    }

    private function formatBytes($bytes, $precision = 2)
    {
        $units = ['B', 'KB', 'MB', 'GB', 'TB'];

        for ($i = 0; $bytes > 1024 && $i < count($units) - 1; $i++) {
            $bytes /= 1024;
        }

        return round($bytes, $precision) . ' ' . $units[$i];
    }
}
